image: emediaorg/php:0.0.1

pipelines:
  default:
    - step:
        name: Laravel + Oxygen Integration Tests
        size: 2x
        caches:
          - composer
          - node
        script:
          - COMPOSER=$(which composer)
          - cd /
          - composer create-project --prefer-dist --remove-vcs laravel/laravel="8.*" laravel_app
          - cd laravel_app
          - php $BITBUCKET_CLONE_DIR/setup/oxygen-install.php --run add-repositories --o_version 5
          - php $BITBUCKET_CLONE_DIR/setup/oxygen-install.php --run set-local-repo --path $BITBUCKET_CLONE_DIR
          - php -d memory_limit=8G $COMPOSER require emedia/oxygen:"@dev" --no-progress --no-interaction --ignore-platform-reqs --no-suggest
          - php artisan oxygen:dashboard:install --name Oxygen --email apps@elegantmedia.com.au --dev_url 127.0.0.1:8000 --dbhost 127.0.0.1 --dbuser appuser --dbpass userpass --mailhost 127.0.0.1 --mailport 1025 --no-interaction
          - composer dump-autoload
          - npm install && npm run dev && npm run dev
          # Install Dusk
          - php -d memory_limit=4G $COMPOSER require laravel/dusk --dev
          - php artisan dusk:install
          - sed -i 's#localhost:9515#127.0.0.1:4444/wd/hub#g' /laravel_app/tests/DuskTestCase.php
          - cp .env .env.dusk.local
          # clear cache after updating .env
          - php artisan config:cache
          - php artisan db:refresh
          # start the test server
          - php artisan serve --host=127.0.0.1 --port=8000 > /dev/null 2>&1 &
          - php artisan dusk --stop-on-error --stop-on-failure --debug --verbose
        services:
          - mysql
          - mail
          - selenium
    - step:
        name: Oxygen Package Tests
        size: 2x
        caches:
          - composer
        script:
          - COMPOSER=$(which composer)
          - php -d memory_limit=8G $COMPOSER install
          - ./vendor/bin/phpunit

definitions:

  # networks: services within the same network can share resources
  # this is how the `app` service can talk to `db` service
  networks:
    app-network:
      driver: bridge

  services:
    mysql:
      image: mysql:8.0
      container_name: dbcontainer
      environment:
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_DATABASE: 'laravel'
        MYSQL_USER: 'appuser'
        MYSQL_PASSWORD: 'userpass'
      networks:
        - app-network

    # mail
    mail:
      image: mailhog/mailhog:latest
      container_name: mailhog
      restart: unless-stopped
      ports:
        - "1025:1025"
        - "8025:8025"
      networks:
        - app-network

    # selenium (for dusk and testing)
    selenium:
      image: selenium/standalone-chrome:3.141.59
      container_name: selenium
      restart: unless-stopped
      shm_size: 2G
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "4444:4444"
      links:
        - app:localhost.devv
      networks:
        - app-network
